/**
 * Represents a user's fantasy persona and aesthetic preferences.
 */
export interface LoreProfile {
  /** The unique identifier for the profile, generated by Firestore */
  id?: string;
  genre: string;
  character_role: string;
  primary_enemies: string;
  visual_aesthetic: string;
  core_motivation: string;
  avatar_url: string;
}

/**
 * Maps a real-world action (e.g., "sweep the floor") to a fantasy action (e.g., "clear the goblin tracks").
 */
export interface ActionMapping {
  real_world_action: string;
  fantasy_action: string;
  objects_involved: string[];
}

/**
 * Represents a single generated image and its accompanying narration text within a story scene.
 */
export interface StoryPicture {
  visual_prompt: string;
  story_beat_direction: string;
}

/**
 * Represents a sequence of story pictures that play after completing a set of actions.
 */
export interface StoryScene {
  scene_id: number;
  actions_covered: number[]; // Indices of ActionMappings covered in this scene
  pictures: StoryPicture[];
}

/**
 * The complete quest plan generated during the Scouting phase.
 */
export interface QuestPlan {
  arc_title: string;
  mappings: ActionMapping[];
  scenes: StoryScene[];
}


